### ISSUE TITLE
[enhancement] Cleanup unused file

### ISSUE THREAD

**Issue by NeuronButter** [cread134/HospitalManagementSystem#1]
Hi there,

When trying to use this repository, my C:\ drive was bloated by 951 bytes due to [this file](https://github.com/cread134/HospitalManagementSystem/blob/master/HMS.Service.Test/HMS%20-%20Backup.Service.Test.csproj) being included in the repo.

Would it be possible to either add this to .gitignore or remove the file (the latter being preferred as .gitignore would require an extra 50 bytes and only have a net difference of 901 without considering filesystem overhead)?

Thank you for your attention into this matter.

**Comment by olivia-stewart-git** [comment]
make a pr for this silly

**Comment by NeuronButter** [comment]
Dear @cread134,

I trust this missive finds you in good health and high spirits.

I am most grateful for the kind invitation extended to me in your recent correspondence to create a pull request. The thoughtfulness of your gesture is truly appreciated.

After careful consideration, however, I find myself regrettably unable to acquiesce to your request at this time. While the opportunity you present is indeed honorable and worthy of interest, my present commitments and obligations render it impractical for me to engage in the matter as proposed.

Please understand that this decision in no way reflects upon the value or merit of your proposition, which I hold in the highest regard. It is merely a reflection of my current constraints.

I remain hopeful that we might find another occasion in the future where our paths may cross in more favorable circumstances. Until such a time, I extend my sincerest regards and best wishes for your continued success.

Thank you once more for your understanding and for considering me for this opportunity.

Yours most respectfully,
@NeuronButter

**Comment by NeuronButter** [comment]
@cread134 Please find the new PR at #2 with an updated repo and .gitignore file
